# Este é um arquivo de configuração
# aqui devemos descrever e definir as 
# gatilhos, etapas, versões e comandos
# que essa maquina/boro deve executar

# Nome do nosso teste
name: Python application test

on: # Quando o evento deve executar

jobs: # Construção passo a passo da sua tarefa
  build: # Etapa de construção/criação

    runs-on: # Em qual plataforma vai rodar

    steps: # Passo a passo da etapa de build
    - uses: actions/chechkout@v2
    
    - name: Set uppython 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.*'

    - name: Run test # name define o nome de uma seção no passo a passo, nesse caso é a ultima etapa, rodar testes
      run: python -m unittest discover -s . # Comando que deve ser executado na máquina/robo que nosso arquivo montou